In [2]:
import numpy as np
A = np.array([[1,2,3], [4,5,6]])
b = np.array([1, 1, 1])
np.dot(A, b)

array([ 6, 15])

In [32]:
import cv2
img = cv2.imread('/Users/zhaosonglin/Desktop/IMG_1006.jpeg')
# print(img)
map_y = np.array([[-9, 1, 4], 
                  [2, 3, 7]], dtype=np.float32)  
map_x = np.array([[3, 6, 5], 
                  [7, 10, 8]], dtype=np.float32)  
mapped_img = cv2.remap(img, map_x, map_y, cv2.INTER_LINEAR)
print(mapped_img)

[[[  0   0   0]
  [ 96  85  71]
  [ 96  85  71]]

 [[100  89  75]
  [ 79  68  54]
  [ 89  78  64]]]


In [13]:
import math
P = 5
Q = 8
u = np.arange(P)[:, None]
v = np.arange(Q)
# dst = np.zeros(P, Q)
result = 100 * np.tan((2*math.pi / 100) * (u-300)) + 300 + v*0
print(result)

[[300.         300.         300.         300.         300.
  300.         300.         300.        ]
 [306.29146673 306.29146673 306.29146673 306.29146673 306.29146673
  306.29146673 306.29146673 306.29146673]
 [312.63293784 312.63293784 312.63293784 312.63293784 312.63293784
  312.63293784 312.63293784 312.63293784]
 [319.07602022 319.07602022 319.07602022 319.07602022 319.07602022
  319.07602022 319.07602022 319.07602022]
 [325.67563604 325.67563604 325.67563604 325.67563604 325.67563604
  325.67563604 325.67563604 325.67563604]]


In [40]:
img = cv2.imread('/Users/zhaosonglin/Desktop/IMG_1006.jpeg')
h, w = img.shape[:2]
print(img.shape)
cx = w/2
cy = h/2

u = cx
v = cy
f = 6000
print(math.atan((0-cx)/f))
mappedX = f * np.tan((2*math.pi / f) * (u-cx)) + cx + v*0
mappedY = (v-cy) * (f**2 + ((f * np.tan((2*math.pi / f) * (u-cx)) + cx)-cx)**2)**0.5 / f + cy
# mappedX = mappedX.astype(np.float32)
# mappedY = mappedY.astype(np.float32)
# print(mappedX.shape)
print(mappedX)
print(mappedY)

(3024, 4032, 3)
-0.3241486313344718
2016.0
1512.0


In [ ]:

dst_pts = np.float32([ kp1[m.queryIdx].pt for m in good_match ]).reshape(-1,1,2)
src_pts = np.float32([ kp2[m.trainIdx].pt for m in good_match ]).reshape(-1,1,2)
M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC,5.0)